#!/usr/bin/bash

rm corpus/enbybooks.json

echo '[' > corpus/enbybooks.notjson
cat corpus/*.json | jq '.[] | .' | sed 's/^}$/},/' >> corpus/enbybooks.notjson
truncate -s -2 corpus/enbybooks.notjson
echo ']' >> corpus/enbybooks.notjson

mv corpus/enbybooks.notjson corpus/enbybooks.json

