#!/usr/bin/bash

ebooks archive alxce_nz corpus/alxce_nz.json
ebooks archive lunarcdr corpus/lunarcdr.json
ebooks consume-all enbybooks corpus/*.json
git add corpus model
git commit -m "Corpus update $(date +'%Y-%m-%d')"
